/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BugInner {
        /**
          * @default ""
         */
        "t": string;
    }
    interface BugOuter {
    }
}
declare global {
    interface HTMLBugInnerElement extends Components.BugInner, HTMLStencilElement {
    }
    var HTMLBugInnerElement: {
        prototype: HTMLBugInnerElement;
        new (): HTMLBugInnerElement;
    };
    interface HTMLBugOuterElement extends Components.BugOuter, HTMLStencilElement {
    }
    var HTMLBugOuterElement: {
        prototype: HTMLBugOuterElement;
        new (): HTMLBugOuterElement;
    };
    interface HTMLElementTagNameMap {
        "bug-inner": HTMLBugInnerElement;
        "bug-outer": HTMLBugOuterElement;
    }
}
declare namespace LocalJSX {
    interface BugInner {
        /**
          * @default ""
         */
        "t"?: string;
    }
    interface BugOuter {
    }
    interface IntrinsicElements {
        "bug-inner": BugInner;
        "bug-outer": BugOuter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bug-inner": LocalJSX.BugInner & JSXBase.HTMLAttributes<HTMLBugInnerElement>;
            "bug-outer": LocalJSX.BugOuter & JSXBase.HTMLAttributes<HTMLBugOuterElement>;
        }
    }
}
